### ISSUE TITLE
ReferenceError: jest is not defined

### ISSUE THREAD

**Issue by wojtekmaj** [wobsoriano/vitest-canvas-mock#4]
This is the error I faced when testing `react-pdf`:

```
ReferenceError: jest is not defined
 ❯ node_modules/jest-canvas-mock/lib/classes/CanvasRenderingContext2D.js:161:19
 ❯ new CanvasRenderingContext2D node_modules/jest-canvas-mock/lib/classes/CanvasRenderingContext2D.js:160:15
 ❯ HTMLCanvasElement.getContext2d node_modules/jest-canvas-mock/lib/mock/prototype.js:28:19
 ❯ HTMLCanvasElement.<anonymous> ../../Open%20source%20projects/react-pdf/node_modules/@vitest/spy/dist/index.js:112:17
 ❯ HTMLCanvasElement.getContext2d [as getContext] ../../Open%20source%20projects/react-pdf/node_modules/tinyspy/dist/index.js:30:20
 ❯ Object.canvasContext src/Page/PageCanvas.jsx:91:23
```

**Comment by alcasas** [comment]
@wojtekmaj I'm having same issue, do you know how to solve it ?

**Comment by treardon17** [comment]
I'm also having this issue

**Comment by alcasas** [comment]
> I'm also having this issue

@treardon17 

I ended up forking jest-canvas-mock in a my github and doing the following:

- install jest-canvas-mock from my repo -> alcasas/jest-canvas-mock#master
- create a file called vitest-canvas-mock.ts
- add the new file in test.setupFiles (in your vite config file)
- add 'jest-canvas-mock' to test.deps.inline (in your vite config file)

this is the content of vitest-canvas-mock.ts:

```
import { afterAll, vi } from 'vitest';
// @ts-expect-error: Global type missing
global.jest = vi;
// eslint-disable-next-line import/first
import getCanvasWindow from 'jest-canvas-mock/src/window'; // here is my fork with changes in the code

const apis = [
  'Path2D',
  'CanvasGradient',
  'CanvasPattern',
  'CanvasRenderingContext2D',
  'DOMMatrix',
  'ImageData',
  'TextMetrics',
  'ImageBitmap',
  'createImageBitmap',
] as const;

const canvasWindow = getCanvasWindow({ document: window.document });

apis.forEach((api) => {
  global[api] = canvasWindow[api];
  global.window[api] = canvasWindow[api];
});

afterAll(() => {
  delete global.jest;
  delete global.window.jest;
});
```

**Comment by nickyvanurk** [comment]
Problem still not solved.

**Comment by wobsoriano** [comment]
Please reopen if the issue continues to exist.

**Comment by aghArdeshir** [comment]
@wobsoriano when using latest version of vitest and vitest-canvas-mock this issue still exists and this workaround still needs to be done:
```
global.jest = vi;
```

Could help if there is a `Troubleshooting` section in the README or straight into the docs somewhere it is mentioned. The only place it is documented now is in this closed issue of the repository.

**Comment by smholsen** [comment]
> ```ts
> declare global {
>   var jest: typeof vi | undefined
> }
> ```

@wobsoriano Can you please explain how this resolves the problem? Thanks!

**Comment by alcasas** [comment]
@nickyvanurk you need to look into the error, then see where is failing, for sure is a method referenced to jest that doesn't exists, so you need to change it in your forked repository to not use that specific reference
