### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ad1992** [wobsoriano/vitest-canvas-mock#8]
Hi @wobsoriano thanks for this package!

I am trying to migrate CRA to Vite in [Excalidraw](https://github.com/excalidraw/excalidraw/pull/6441) and running into issues when migrating tests. We are using `jest-canvas-mock` and thats how I came across this library when migrating to Vite.
However I am getting 👇🏻 error

<img width="831" alt="Screenshot 2023-06-22 at 12 44 02 PM" src="https://github.com/wobsoriano/vitest-canvas-mock/assets/11256141/dc2fd463-a2c2-4229-869d-cdfd4ec4a386">

In addition when I disable the `threads` as suggested in the `Readme`, the tests just hangs and I have to manually terminate. 

Could you tell me how can I fix it ?

**Comment by ad1992** [comment]
On further debugging, this is where its thrown from in `jest-canvas-mock` in `prototype.js`. The `win` object doesn't have `HTMLCanvasElement` hence the error

![Screenshot 2023-06-22 at 3 58 16 PM](https://github.com/wobsoriano/vitest-canvas-mock/assets/11256141/0051bdc9-d17c-4964-b526-dcadb0dae698)

**Comment by ad1992** [comment]
There is an issue for the same opened in [jest-canvas-mock](https://github.com/hustcc/jest-canvas-mock/issues/115)

**Comment by jenaicprb** [comment]
> On further debugging, this is where its thrown from in `jest-canvas-mock` in `prototype.js`. The `win` object doesn't have `HTMLCanvasElement` hence the error
> 
> ![Screenshot 2023-06-22 at 3 58 16 PM](https://user-images.githubusercontent.com/11256141/247902743-0051bdc9-d17c-4964-b526-dcadb0dae698.png)

Hi,

Would you have a gist with the exact steps you followed?
Seems you've patched the code in jest-canvas-mock, then use selective version resolutions?

**Comment by finishedcoot** [comment]
I have the same problem
I tried the solution above by @jenaicprb , but I use npm so my alternative to yarn's "resolution" was this:
`"overrides": {
    "vitest-canvas-mock": {
      "jest-canvas-mock": "2.4.0"
    }
  }`
  but I still get the same error

**Comment by wobsoriano** [comment]
Latest version uses `jest-canvas-mock@2.4.0`, still getting the error?

**Comment by ad1992** [comment]
@wobsoriano the issue seems to be fixed in `jest-canvas-mock@2.5.2` reference - https://github.com/hustcc/jest-canvas-mock/pull/116 , can you release a patch version for vitest-canvas-mock ?

**Comment by wobsoriano** [comment]
@ad1992 updated to use `jest-canvas-mock@2.5.2`!

**Comment by ad1992** [comment]
> @ad1992 updated to use `jest-canvas-mock@2.5.2`! Let me know if that still works.

A little late here, but yes everything works well so I am closing this.

Thanks @wobsoriano ✨
