### ISSUE TITLE
Configuration with Vitest 0.34 

### ISSUE THREAD

**Issue by titenis** [wobsoriano/vitest-canvas-mock#9]
Starting with Vitest 0.34 `deps.inline` is deprecated
`Vitest  "deps.inline" is deprecated. If you rely on vite-node directly, use "server.deps.inline" instead. Otherwise, consider using "deps.optimizer.web.include"`

How configuration should be migrated?
```
deps: {
      inline: ['vitest-canvas-mock'],
    },
```

**Comment by wobsoriano** [comment]
I think that depends on your project? But pretty sure you're gonna go with `deps.optimizer.web.include`.

**Comment by acelaya** [comment]
> I think that depends on your project? But pretty sure you're gonna go with `deps.optimizer.web.include`.

I can confirm this worked for me.

```diff
     deps: {
-      inline: ['vitest-canvas-mock'],
+      optimizer: {
+        web: {
+          include: ['vitest-canvas-mock'],
+        },
+      },
     },
```

The funny thing is that vitest actually suggest this, but I didn't notice at first:

![image](https://github.com/wobsoriano/vitest-canvas-mock/assets/2719332/39604ab3-a60e-4de6-9687-10c57875c1ae)

**Comment by wobsoriano** [comment]
Updated README as well. Thanks!
